project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

import squirrel_tracker.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('squirrel_tracker.urls')),
    path('map/', views.show_map, name='show_map'),
    path('sightings/', include('squirrel_tracker.urls')),
]

squirrel_tracker/urls.py
from django.urls import path
from django.urls import re_path

from . import views

app_name = 'squirrel_tracker'

urlpatterns = [
    path('', views.new_index, name='index'),
    re_path(r'(?P<unique_squirrel_id>[0-9]+[A-Z]-[AP]M-[0-9]{4}-[0-9]{2})/$', views.detail, name='detail'),
    path('add/', views.add_sighting, name='add'),
    path('stats/', views.stats, name='stats'),
    path('sightings/', views.index, name='sightings'),
]

squirrel_tracker/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.core.validators import RegexValidator


class Sighting(models.Model):

    latitude = models.FloatField(
        help_text='Latitude'
    )

    longitude = models.FloatField(
        help_text='Longitude'
    )

    unique_squirrel_id = models.CharField(
        max_length=50,
        help_text=_('Unique Squirrel ID'),
        unique=True,
        validators=[
            RegexValidator(
                '^[0-9]+[A-Z]-[AP]M-[0-9]{4}-[0-9]{2}$',
                message='Incorrect format of Unique Squirrel ID',
                code='invalid_id'
            )
        ]
    )

    hectare = models.CharField(
        max_length=10,
        help_text=_('Hectare')
    )

    AM = 'AM'
    PM = 'PM'
    SHIFT_CHOICES = [
        (AM, 'AM'),
        (PM, 'PM')
    ]
    shift = models.CharField(
        max_length=10,
        help_text=_('Shift'),
        choices=SHIFT_CHOICES
    )

    date = models.DateField(
        help_text=_('Date')
    )

    hectare_squirrel_number = models.IntegerField(
        default=1,
        help_text=_('Hectare Squirrel Number')
    )

    ADULT = 'Adult'
    JUVENILE = 'Juvenile'
    QUESTION_MARK = '?'

    AGE_CHOICES = [
        (ADULT, _('Adult')),
        (JUVENILE, _('Juvenile')),
        (QUESTION_MARK, _('?')),
    ]

    age = models.CharField(
        max_length=50,
        help_text='Age',
        choices=AGE_CHOICES,
        blank=True
    )

    primary_fur_color = models.CharField(
        max_length=100,
        help_text='Primary Fur Color',
        blank=True
    )

    highlight_fur_color = models.CharField(
        max_length=100,
        help_text='Highlight Fur Color',
        default='',
        blank=True
    )

    GROUND_PLANE = 'Ground Plane'
    ABOVE_GROUND = 'Above Ground'

    LOCATION_CHOICES = [
        (GROUND_PLANE, _('ground plane')),
        (ABOVE_GROUND, _('above ground')),
    ]

    location = models.CharField(
        max_length=50,
        help_text='Location',
        choices=LOCATION_CHOICES,
        blank=True
    )

    specific_location = models.CharField(
        max_length=100,
        help_text='Specific Location',
        default='',
        blank=True
    )

    running = models.BooleanField(
        help_text='Whether or not the squirrel was seen running'
    )

    chasing = models.BooleanField(
        help_text='Whether or not the squirrel was seen chasing'
    )

    climbing = models.BooleanField(
        help_text='Whether or not the squirrel was seen climbing'
    )

    eating = models.BooleanField(
        help_text='Whether or not the squirrel was seen eating'
    )

    foraging = models.BooleanField(
        help_text='Whether or not the squirrel is foraging'
    )

    other_activities = models.CharField(
        max_length=200,
        help_text='Other Activities',
        blank=True
    )

    kuks = models.BooleanField(
        help_text="Whether or not the squirrel was heard kukking"
    )

    quaas = models.BooleanField(
        help_text="Whether or not the squirrel was heard quaaing"
    )

    moans = models.BooleanField(
        help_text='Whether or not the squirrel was heard moaning'
    )

    tail_flags = models.BooleanField(
        help_text="Whether or not the squirrel was seen flagging its tail"
    )

    tail_twitches = models.BooleanField(
        help_text="Whether or not the squirrel was seen twitching its tail"
    )

    approaches = models.BooleanField(
        help_text="Whether or not the squirrel was seen approaching human"
    )

    indifferent = models.BooleanField(
        help_text="Whether or not the squirrel was indifferent to human presence"
    )

    runs_from = models.BooleanField(
        help_text='Whether or not the squirrel was seen running away from human'
    )

squirrel_tracker/forms.py
from django import forms
from squirrel_tracker.models import Sighting


class UpdateForm(forms.ModelForm):

    class Meta:
        model = Sighting
        fields = [
            'latitude',
            'longitude',
            'shift',
            'date',
            'age'
        ]


class AddSightingForm(forms.ModelForm):
    class Meta:
        model = Sighting
        fields = [
            'latitude',
            'longitude',
            'unique_squirrel_id',
            'shift',
            'date',
            'age',
            'primary_fur_color',
            'location',
            'specific_location',
            'running',
            'chasing',
            'climbing',
            'eating',
            'foraging',
            'other_activities',
            'kuks',
            'quaas',
            'moans',
            'tail_flags',
            'tail_twitches',
            'approaches',
            'indifferent',
            'runs_from'
        ]

squirrel_tracker/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib import messages

from .models import Sighting
from .forms import UpdateForm
from .forms import AddSightingForm


def index(request):

    def parse_date(date):
        date = str(date)

        return date

    sightings = Sighting.objects.all()
    for i in range(len(sightings)):
        sightings[i].date = parse_date(sightings[i].date)
    context = {
        'sightings': sightings
    }
    return render(request, 'squirrel_tracker/index.html', context)


def new_index(request):

    def parse_date(date):
        date = str(date)

        return date

    sightings = Sighting.objects.all()
    for i in range(len(sightings)):
        sightings[i].date = parse_date(sightings[i].date)
    context = {
        'sightings': sightings
    }
    return render(request, 'squirrel_tracker/new_index.html', context)


def detail(request, unique_squirrel_id):
    if request.method == 'POST':
        form = UpdateForm(request.POST)
        sighting = Sighting.objects.get(unique_squirrel_id=unique_squirrel_id)
        if form.is_valid():
            latitude = form.cleaned_data['latitude']
            longitude = form.cleaned_data['longitude']
            shift = form.cleaned_data['shift']
            date = form.cleaned_data['date']
            age = form.cleaned_data['age']

            sighting.latitude = latitude
            sighting.longitude = longitude
            sighting.shift = shift
            sighting.date = date
            sighting.age = age

            sighting.save()
            messages.success(request, 'The sighting was successfully updated!')

        context = {
            'sighting': sighting,
            'form': form
        }

    else:
        sighting = get_object_or_404(Sighting, unique_squirrel_id=unique_squirrel_id)
        latitude = sighting.latitude
        longitude = sighting.longitude
        shift = sighting.shift
        date = sighting.date
        age = sighting.age
        form = UpdateForm(
            initial={
                'latitude': latitude,
                'longitude': longitude,
                'shift': shift,
                'date': date,
                'age': age
            }
        )
        context = {
            'sighting': sighting,
            'form': form
        }
    return render(request, 'squirrel_tracker/detail.html', context)


def add_sighting(request):
    if request.method == 'POST':
        form = AddSightingForm(request.POST)
        if form.is_valid():
            latitude = form.cleaned_data['latitude']
            longitude = form.cleaned_data['longitude']
            unique_squirrel_id = form.cleaned_data['unique_squirrel_id']
            shift = form.cleaned_data['shift']
            date = form.cleaned_data['date']
            age = form.cleaned_data['age']
            primary_fur_color = form.cleaned_data['primary_fur_color']
            location = form.cleaned_data['location']
            specific_location = form.cleaned_data['specific_location']
            running = form.cleaned_data['running']
            chasing = form.cleaned_data['chasing']
            eating = form.cleaned_data['eating']
            foraging = form.cleaned_data['foraging']
            other_activities = form.cleaned_data['other_activities']
            kuks = form.cleaned_data['kuks']
            quaas = form.cleaned_data['quaas']
            moans = form.cleaned_data['moans']
            tail_flags = form.cleaned_data['tail_flags']
            tail_twitches = form.cleaned_data['tail_twitches']
            approaches = form.cleaned_data['approaches']
            indifferent = form.cleaned_data['indifferent']
            runs_from = form.cleaned_data['runs_from']
            climbing = form.cleaned_data['climbing']

            sighting = Sighting()
            sighting.unique_squirrel_id = unique_squirrel_id
            sighting.latitude = latitude
            sighting.longitude = longitude
            sighting.shift = shift
            sighting.date = date
            sighting.age = age
            sighting.primary_fur_color = primary_fur_color
            sighting.location = location
            sighting.specific_location = specific_location
            sighting.running = running
            sighting.chasing = chasing
            sighting.eating = eating
            sighting.foraging = foraging
            sighting.other_activities = other_activities
            sighting.kuks = kuks
            sighting.quaas = quaas
            sighting.moans = moans
            sighting.tail_flags = tail_flags
            sighting.tail_twitches = tail_twitches
            sighting.approaches = approaches
            sighting.indifferent = indifferent
            sighting.runs_from = runs_from
            sighting.climbing = climbing

            sighting.save()

            form = AddSightingForm()

            messages.success(request, 'A new sighting was successfully added!')

    else:
        form = AddSightingForm()

    return render(request, 'squirrel_tracker/add.html', {'form': form})


def show_map(request):
    sightings = Sighting.objects.all()[:100]
    context = {
        'sightings': sightings
    }
    return render(request, 'squirrel_tracker/map.html', context)


def stats(request):
    num_of_sightings = Sighting.objects.all().count()
    num_of_squirrel = Sighting.objects.values("unique_squirrel_id").distinct().count()
    juvenile_age = Sighting.objects.filter(age='Juvenile').count()
    gray_fur = Sighting.objects.filter(primary_fur_color='Gray').count()
    ground_plane_location = Sighting.objects.filter(
        location='Ground Plane').count()
    running = Sighting.objects.filter(running='True').count()
    context = {
        'num_of_sightings': num_of_sightings,
        'num_of_squirrel': num_of_squirrel,
        'juvenile_age': juvenile_age,
        'gray_fur': gray_fur,
        'ground_plane_location': ground_plane_location,
        'running': running,
    }

    return render(request, 'squirrel_tracker/stats.html', context)

squirrel_tracker/templates/squirrel_tracker/add.html
<!doctype html>
<html>

<head>
	<meta charset='utf-8'>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style>
	</style>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
    <body bgcolor="e9e4cd"></body>
<style>
    .button {
      display: inline-block;
      zoom: 1; 
      *display: inline;
      vertical-align: baseline;
      margin: 0 2px;
      outline: none;
      cursor: pointer;
      text-align: center;
      text-decoration: none;
      font: 14px/100% Arial, Helvetica, sans-serif;
      padding: .5em 2em .55em;
      text-shadow: 0 1px 1px rgba(0,0,0,.3);
      -webkit-border-radius: .5em; 
      -moz-border-radius: .5em;
      border-radius: .5em;
      -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.2);
      -moz-box-shadow: 0 1px 2px rgba(0,0,0,.2);
      box-shadow: 0 1px 2px rgba(0,0,0,.2);
  }
  .blue {
      color: #030303;
      border: solid 1px #0c7dda;
      background: #0c7dda;
      background: -webkit-gradient(linear, left top, left bottom, from(#0c7dda), to(#4e96d1));
      background: -moz-linear-gradient(top,  #faa51a,  #f47a20);
      filter:  progid:DXImageTransform.Microsoft.gradient(startColorstr='#23cea9', endColorstr='#20edf4');
  }
body{
    padding-top: 20px;
        padding-left: 10px; padding-right: 10px;
    }
</style>
{% load static %}

{% block main %}
    <div class="container">
        {% if messages %}
            <div class="messages" >
                {% for message in messages %}
                    <div class="alert alert-success">
                        <strong>{{ message }}</strong>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
        {% endif %}
        
        <h1>Add a New Squirrel Sighting here!</h1>
        <h3>Please input what you saw here</h3>
        <form action="{% url 'squirrel_tracker:add' %}" method="post">
            {% csrf_token %}
<!--            {{ form }}-->
            {% for field in form %}
                {{ field.label }}
                {{ field }}
                <br>
            {% endfor %}
            <button class="button blue" type="submit">Add</button>
            <a class="button blue" href="/"> Back to home page </a>
        </form>
    </div>
{% endblock %}

squirrel_tracker/templates/squirrel_tracker/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Squirrel Tracker{% block title %}{% endblock %}</title>
</head>
<body  bgcolor="e9e4cd">

    <main role="main">
        {% block main %}
        {% endblock %}
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

squirrel_tracker/templates/squirrel_tracker/detail.html
{% extends 'squirrel_tracker/base.html' %}

{% load static %}

{% block title %} - {{ sighting.unique_squirrel_id }} details page{% endblock %}

{% block main %}
    <div class="container">
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-success">
                        <strong>{{ message }}</strong>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
        {% endif %}
        <table class="table">
            <thead>
                 <tr>
                    <th scope="col">#</th>
                    <th scope="col">value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">Unique Squirrel ID</th>
                    <td>{{ sighting.unique_squirrel_id }}</td>
                </tr>
                <tr>
                    <th scope="row">Latitude</th>
                    <td>{{ sighting.latitude }}</td>
                </tr>
                <tr>
                    <th scope="row">Longitude</th>
                    <td>{{ sighting.longitude }}</td>
                </tr>
                <tr>
                    <th scope="row">Shift</th>
                    <td>{{ sighting.shift }}</td>
                </tr>
                <tr>
                    <th scope="row">Date</th>
                    <td>{{ sighting.date }}</td>
                </tr>
                <tr>
                    <th scope="row">Age</th>
                    <td>{{ sighting.age }}</td>
                </tr>
            </tbody>
        </table>
        <br>
        <h3>Update sighting here!</h3>
        <form action="{% url 'squirrel_tracker:detail' sighting.unique_squirrel_id %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                {{ field.label }}
                {{ field }}
                <br>
            {% endfor %}
            <button class="btn btn-outline-secondary" type="submit">Update</button>
            
        </form>
    </div>
{% endblock %}

squirrel_tracker/templates/squirrel_tracker/index.html
{% extends 'squirrel_tracker/base.html' %}

{% load static %}

{% block title %} - All Sightings{% endblock %}

{% block main %}
    <div class="container">
        <a href="/">Back to home page </a>
        <h1>Squirrel List</h1>
        <a href="add/">Add a New Squirrel Sighting</a>
        
        <ul class="list-group">
            {% for sighting in sightings %}
                <li class="list-group-item">

                    <h5>{{ sighting.unique_squirrel_id }}</h5>
                    <p>
                        {{ sighting.date }}
                    </p>
                    <a href="{{ sighting.unique_squirrel_id }}/">Details</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}
</html>

squirrel_tracker/templates/squirrel_tracker/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
    <title>Squirrel Map</title>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for sighting in sightings %}
          var point_lat_lon = [{{ sighting.latitude }}, {{ sighting.longitude }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

squirrel_tracker/templates/squirrel_tracker/new_index.html
<!doctype html>
<html>

<head>
	<meta charset='utf-8'>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style>
	</style>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

    <body style="text-align:center" bgcolor="e9e4cd"></body>
    <h1>Squirrel Tracker</h1>

    
    <img src="https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fdpic.tiankong.com%2Fxv%2Fl5%2FQJ8222690110.jpg&refer=http%3A%2F%2Fdpic.tiankong.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1620996170&t=2438273e3d0ceecb0d5eff9404ed1628" alt="Squirrel Pictures" height=450>
    <h4><font color='666666'>IEOR4501 Final Project</font></h4>
    <h5><font color='666666'>Jiawei Zhang & Hanjing Luo</font></h5>
    
    <style>
        .button {
      display: inline-block;
      zoom: 1; 
      *display: inline;
      vertical-align: baseline;
      margin: 0 2px;
      outline: none;
      cursor: pointer;
      text-align: center;
      text-decoration: none;
      font: 14px/100% Arial, Helvetica, sans-serif;
      padding: .5em 2em .55em;
      text-shadow: 0 1px 1px rgba(0,0,0,.3);
      -webkit-border-radius: .5em; 
      -moz-border-radius: .5em;
      border-radius: .5em;
      -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.2);
      -moz-box-shadow: 0 1px 2px rgba(0,0,0,.2);
      box-shadow: 0 1px 2px rgba(0,0,0,.2);
  }

  

  .medium {
      font-size: 20px;
      padding: .4em 1.5em .42em;
  }
  .small {
      font-size: 11px;
      padding: .2em 1em .275em;
  }
  
  .blue {
      color: #030303;
      border: solid 1px #0c7dda;
      background: #0c7dda;
      background: -webkit-gradient(linear, left top, left bottom, from(#0c7dda), to(#4e96d1));
      background: -moz-linear-gradient(top,  #faa51a,  #f47a20);
      filter:  progid:DXImageTransform.Microsoft.gradient(startColorstr='#23cea9', endColorstr='#20edf4');
  }

  body{
    padding-top: 70px;
        padding-left: 10px; padding-right: 10px;
      }
  </style>
  <br>	  
  <a class="button blue medium" href="add/"> Add New Squirrel </a>
              
  <a class="button blue medium" href="sightings/"> Squirrel Sightings </a>
               
    <a class="button blue medium" href="stats/">Stats of Squirrels </a>	
          
    <a class="button blue medium" href="map/"> Map of Squirrels </a>
</br>    
</html>

squirrel_tracker/templates/squirrel_tracker/stats.html
<!doctype html>
<html>

<head>
	<meta charset='utf-8'>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style>
	</style>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<h1 class="text-center mt-5">Sighting Stats</h1>
{% block content %}
<form method='GET'>

	<style>
		table,
		table tr th,
		table tr td {
			border: 2px solid white;
		}

		table {
			width: 900px;
			min-height: 50px;
			line-height: 50px;
			text-align: center;
			border-collapse: collapse;
		}
		.button {
			display: inline-block;
			zoom: 1; 
			*display: inline;
			vertical-align: baseline;
			margin: 0 2px;
			outline: none;
			cursor: pointer;
			text-align: center;
			text-decoration: none;
			font: 14px/100% Arial, Helvetica, sans-serif;
			padding: .5em 2em .55em;
			text-shadow: 0 1px 1px rgba(0,0,0,.3);
			-webkit-border-radius: .5em; 
			-moz-border-radius: .5em;
			border-radius: .5em;
			-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.2);
			-moz-box-shadow: 0 1px 2px rgba(0,0,0,.2);
			box-shadow: 0 1px 2px rgba(0,0,0,.2);
  		}
		.blue {
			color: #030303;
			border: solid 1px #0c7dda;
			background: #0c7dda;
			background: -webkit-gradient(linear, left top, left bottom, from(#0c7dda), to(#4e96d1));
			background: -moz-linear-gradient(top,  #faa51a,  #f47a20);
			filter:  progid:DXImageTransform.Microsoft.gradient(startColorstr='#23cea9', endColorstr='#20edf4');
		}
		body{
			padding-top: 20px;
				padding-left: 10px; padding-right: 10px;
			}

	</style>

	<table align='center' class="mt-1 table table-striped">
		<tr class="bg-info">
			<th> Unique Sightings</th>
            <th> Unique Squirrels</th>
		</tr>
		<tr class="bg-warning">
			<td>{{ num_of_sightings }}</td>
            <td>{{ num_of_squirrel }}</td>

		</tr>
		</center>
	</table>
    
    <table align='center' class="mt-1 table table-striped">
		<tr class="bg-info">
			<th> Juvenile Age Squirrels</th>
			<th> Squirrels with Gray Fur</th>
			<th> Squirrels on the Ground</th>
			<th> Squirrels Running</th>
		</tr>
		<tr class="bg-warning">
			<td>{{ juvenile_age }}</td>
			<td>{{ gray_fur }}</td>
			<td>{{ ground_plane_location }}</td>
			<td>{{ running }}</td>
		</tr>
		</center>
	</table>
</form>

<a class="button blue" href="/"> Back to home page </a>
{% endblock %}
<script src="https://code.jquery.com/jquery-3.4.0.min.js"
	integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
	integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
	crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
	integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
	crossorigin="anonymous"></script>

</html>